version: "3.8"
services:
  api:
    #image: joon/nestjs-dockerized
          build: 
            dockerfile: Dockerfile
            context: .
          depends_on:
            - postgres
          environment:
            DATABASE_URL: postgres://user:password@db:5432/db
            NODE_ENV: development
            PORT: 3000
          ports:
            - "8080:3000"
  
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password

